name: Deploy NestJS to Vercel

on:
  push:
    branches:
      - main  # veya production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Vercel’in desteklediği sürüm

      - name: Install dependencies
        run: npm install

      - name: Build NestJS
        run: npm run build

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Deploy to Vercel
        run: vercel --prod --token=$VERCEL_TOKEN --confirm --org-id=$VERCEL_ORG_ID --project-id=$VERCEL_PROJECT_ID
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
